name: Build and deploy .NET Core application to Web App EyadAzure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: EyadAzure
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 10.0.x
  WORKING_DIRECTORY: CICD

jobs:
  build:
    environment: EyadAzure_Env
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build

      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Show published files
        run: dir "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    environment: EyadAzure_Env
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Show downloaded files
        run: dir "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.EyadAzure_CLIENT_ID_B414 }}
          tenant-id: ${{ vars.EyadAzure_TENANT_ID_B414 }}
          subscription-id: ${{ vars.EyadAzure_SUBSCRIPTION_ID_B414 }}

      - name: Deploy to Azure WebApp
        run: |
          Compress-Archive -Path "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}\*" -DestinationPath "app.zip" -Force
          az webapp deploy `
            --resource-group "azureapp-auto-alerts-ce9349-seifhendawy1_gmail_com" `
            --name "${{ env.AZURE_WEBAPP_NAME }}" `
            --src-path "app.zip" `
            --type zip `
            --clean true `
            --restart true